name: Sync Leetcode

on:
  workflow_dispatch: # Isse aap manually jab chahe button daba kar sync kar sakte hain
  schedule:
    - cron: '0 8 * * *' # Yeh har din automatic subah 8 baje chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Leetcode Sync
        uses: joshcai/leetcode-sync@v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'solutions' # Is folder ke andar saare questions save honge
